# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Desktop/Coding/Verilog/practice_lab/practice_lab.srcs/sources_1/bd/prac_bd/ip/prac_bd_rst_ps7_0_100M_2/prac_bd_rst_ps7_0_100M_2.xci
# IP: The module: 'prac_bd_rst_ps7_0_100M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Desktop/Coding/Verilog/practice_lab/practice_lab.srcs/sources_1/bd/prac_bd/ip/prac_bd_rst_ps7_0_100M_2/prac_bd_rst_ps7_0_100M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'prac_bd_rst_ps7_0_100M_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Desktop/Coding/Verilog/practice_lab/practice_lab.srcs/sources_1/bd/prac_bd/ip/prac_bd_rst_ps7_0_100M_2/prac_bd_rst_ps7_0_100M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'prac_bd_rst_ps7_0_100M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Desktop/Coding/Verilog/practice_lab/practice_lab.srcs/sources_1/bd/prac_bd/ip/prac_bd_rst_ps7_0_100M_2/prac_bd_rst_ps7_0_100M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prac_bd_rst_ps7_0_100M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Desktop/Coding/Verilog/practice_lab/practice_lab.srcs/sources_1/bd/prac_bd/ip/prac_bd_rst_ps7_0_100M_2/prac_bd_rst_ps7_0_100M_2.xci
# IP: The module: 'prac_bd_rst_ps7_0_100M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Desktop/Coding/Verilog/practice_lab/practice_lab.srcs/sources_1/bd/prac_bd/ip/prac_bd_rst_ps7_0_100M_2/prac_bd_rst_ps7_0_100M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'prac_bd_rst_ps7_0_100M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Desktop/Coding/Verilog/practice_lab/practice_lab.srcs/sources_1/bd/prac_bd/ip/prac_bd_rst_ps7_0_100M_2/prac_bd_rst_ps7_0_100M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'prac_bd_rst_ps7_0_100M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Desktop/Coding/Verilog/practice_lab/practice_lab.srcs/sources_1/bd/prac_bd/ip/prac_bd_rst_ps7_0_100M_2/prac_bd_rst_ps7_0_100M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prac_bd_rst_ps7_0_100M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
