# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/User/Desktop/ELD LAB/ak/ak.srcs/sources_1/ip/floating_point_adder/floating_point_adder.xci
# IP: The module: 'floating_point_adder' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/Desktop/ELD LAB/ak/ak.srcs/sources_1/ip/floating_point_adder/floating_point_adder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_adder'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/User/Desktop/ELD LAB/ak/ak.srcs/sources_1/ip/floating_point_adder/floating_point_adder.xci
# IP: The module: 'floating_point_adder' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/Desktop/ELD LAB/ak/ak.srcs/sources_1/ip/floating_point_adder/floating_point_adder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_adder'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
