# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/prac_bd/prac_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prac_bd || ORIG_REF_NAME==prac_bd} -quiet] -quiet

# IP: bd/prac_bd/ip/prac_bd_processing_system7_0_0/prac_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prac_bd_processing_system7_0_0 || ORIG_REF_NAME==prac_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/prac_bd/ip/prac_bd_axi_dma_0_0/prac_bd_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prac_bd_axi_dma_0_0 || ORIG_REF_NAME==prac_bd_axi_dma_0_0} -quiet] -quiet

# IP: bd/prac_bd/ip/prac_bd_xfft_0_0/prac_bd_xfft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prac_bd_xfft_0_0 || ORIG_REF_NAME==prac_bd_xfft_0_0} -quiet] -quiet

# IP: bd/prac_bd/ip/prac_bd_axi_smc_2/prac_bd_axi_smc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prac_bd_axi_smc_2 || ORIG_REF_NAME==prac_bd_axi_smc_2} -quiet] -quiet

# IP: bd/prac_bd/ip/prac_bd_rst_ps7_0_100M_2/prac_bd_rst_ps7_0_100M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prac_bd_rst_ps7_0_100M_2 || ORIG_REF_NAME==prac_bd_rst_ps7_0_100M_2} -quiet] -quiet

# IP: bd/prac_bd/ip/prac_bd_ps7_0_axi_periph_2/prac_bd_ps7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prac_bd_ps7_0_axi_periph_2 || ORIG_REF_NAME==prac_bd_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/prac_bd/ip/prac_bd_floating_point_0_0/prac_bd_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prac_bd_floating_point_0_0 || ORIG_REF_NAME==prac_bd_floating_point_0_0} -quiet] -quiet

# IP: bd/prac_bd/ip/prac_bd_axis_dwidth_converter_0_1/prac_bd_axis_dwidth_converter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prac_bd_axis_dwidth_converter_0_1 || ORIG_REF_NAME==prac_bd_axis_dwidth_converter_0_1} -quiet] -quiet

# IP: bd/prac_bd/ip/prac_bd_xlconstant_0_1/prac_bd_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prac_bd_xlconstant_0_1 || ORIG_REF_NAME==prac_bd_xlconstant_0_1} -quiet] -quiet

# IP: bd/prac_bd/ip/prac_bd_floating_point_1_0/prac_bd_floating_point_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prac_bd_floating_point_1_0 || ORIG_REF_NAME==prac_bd_floating_point_1_0} -quiet] -quiet

# IP: bd/prac_bd/ip/prac_bd_xlconstant_0_2/prac_bd_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prac_bd_xlconstant_0_2 || ORIG_REF_NAME==prac_bd_xlconstant_0_2} -quiet] -quiet

# IP: bd/prac_bd/ip/prac_bd_xlconstant_1_0/prac_bd_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prac_bd_xlconstant_1_0 || ORIG_REF_NAME==prac_bd_xlconstant_1_0} -quiet] -quiet

# IP: bd/prac_bd/ip/prac_bd_auto_pc_0/prac_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prac_bd_auto_pc_0 || ORIG_REF_NAME==prac_bd_auto_pc_0} -quiet] -quiet

# IP: bd/prac_bd/ip/prac_bd_system_ila_0_0/prac_bd_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prac_bd_system_ila_0_0 || ORIG_REF_NAME==prac_bd_system_ila_0_0} -quiet] -quiet

# XDC: bd/prac_bd/prac_bd_ooc.xdc
