# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/fft/fft.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft || ORIG_REF_NAME==fft} -quiet] -quiet

# IP: bd/fft/ip/fft_processing_system7_0_0/fft_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_processing_system7_0_0 || ORIG_REF_NAME==fft_processing_system7_0_0} -quiet] -quiet

# IP: bd/fft/ip/fft_axi_dma_0_0/fft_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_axi_dma_0_0 || ORIG_REF_NAME==fft_axi_dma_0_0} -quiet] -quiet

# IP: bd/fft/ip/fft_xfft_0_0/fft_xfft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_xfft_0_0 || ORIG_REF_NAME==fft_xfft_0_0} -quiet] -quiet

# IP: bd/fft/ip/fft_xlconstant_0_0/fft_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_xlconstant_0_0 || ORIG_REF_NAME==fft_xlconstant_0_0} -quiet] -quiet

# IP: bd/fft/ip/fft_xlconstant_1_0/fft_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_xlconstant_1_0 || ORIG_REF_NAME==fft_xlconstant_1_0} -quiet] -quiet

# IP: bd/fft/ip/fft_axis_dwidth_converter_0_0/fft_axis_dwidth_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_axis_dwidth_converter_0_0 || ORIG_REF_NAME==fft_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/fft/ip/fft_floating_point_0_0/fft_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_floating_point_0_0 || ORIG_REF_NAME==fft_floating_point_0_0} -quiet] -quiet

# IP: bd/fft/ip/fft_axi_smc_0/fft_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_axi_smc_0 || ORIG_REF_NAME==fft_axi_smc_0} -quiet] -quiet

# IP: bd/fft/ip/fft_rst_ps7_0_50M_0/fft_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_rst_ps7_0_50M_0 || ORIG_REF_NAME==fft_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/fft/ip/fft_ps7_0_axi_periph_0/fft_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_ps7_0_axi_periph_0 || ORIG_REF_NAME==fft_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/fft/ip/fft_system_ila_0_0/fft_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_system_ila_0_0 || ORIG_REF_NAME==fft_system_ila_0_0} -quiet] -quiet

# IP: bd/fft/ip/fft_auto_pc_0/fft_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_auto_pc_0 || ORIG_REF_NAME==fft_auto_pc_0} -quiet] -quiet

# XDC: bd/fft/fft_ooc.xdc
