# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/fft_8pt_bd/fft_8pt_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_8pt_bd || ORIG_REF_NAME==fft_8pt_bd} -quiet] -quiet

# IP: bd/fft_8pt_bd/ip/fft_8pt_bd_processing_system7_0_0/fft_8pt_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_8pt_bd_processing_system7_0_0 || ORIG_REF_NAME==fft_8pt_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/fft_8pt_bd/ip/fft_8pt_bd_axi_dma_0_0/fft_8pt_bd_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_8pt_bd_axi_dma_0_0 || ORIG_REF_NAME==fft_8pt_bd_axi_dma_0_0} -quiet] -quiet

# IP: bd/fft_8pt_bd/ip/fft_8pt_bd_xfft_0_0/fft_8pt_bd_xfft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_8pt_bd_xfft_0_0 || ORIG_REF_NAME==fft_8pt_bd_xfft_0_0} -quiet] -quiet

# IP: bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/fft_8pt_bd_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_8pt_bd_axi_smc_0 || ORIG_REF_NAME==fft_8pt_bd_axi_smc_0} -quiet] -quiet

# IP: bd/fft_8pt_bd/ip/fft_8pt_bd_rst_ps7_0_100M_0/fft_8pt_bd_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_8pt_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==fft_8pt_bd_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/fft_8pt_bd/ip/fft_8pt_bd_ps7_0_axi_periph_0/fft_8pt_bd_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_8pt_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==fft_8pt_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/fft_8pt_bd/ip/fft_8pt_bd_xlconstant_0_0/fft_8pt_bd_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_8pt_bd_xlconstant_0_0 || ORIG_REF_NAME==fft_8pt_bd_xlconstant_0_0} -quiet] -quiet

# IP: bd/fft_8pt_bd/ip/fft_8pt_bd_xlconstant_1_0/fft_8pt_bd_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_8pt_bd_xlconstant_1_0 || ORIG_REF_NAME==fft_8pt_bd_xlconstant_1_0} -quiet] -quiet

# IP: bd/fft_8pt_bd/ip/fft_8pt_bd_auto_pc_0/fft_8pt_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_8pt_bd_auto_pc_0 || ORIG_REF_NAME==fft_8pt_bd_auto_pc_0} -quiet] -quiet

# IP: bd/fft_8pt_bd/ip/fft_8pt_bd_floating_point_0_0/fft_8pt_bd_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_8pt_bd_floating_point_0_0 || ORIG_REF_NAME==fft_8pt_bd_floating_point_0_0} -quiet] -quiet

# IP: bd/fft_8pt_bd/ip/fft_8pt_bd_xlconstant_2_0/fft_8pt_bd_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_8pt_bd_xlconstant_2_0 || ORIG_REF_NAME==fft_8pt_bd_xlconstant_2_0} -quiet] -quiet

# IP: bd/fft_8pt_bd/ip/fft_8pt_bd_axis_dwidth_converter_0_0/fft_8pt_bd_axis_dwidth_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_8pt_bd_axis_dwidth_converter_0_0 || ORIG_REF_NAME==fft_8pt_bd_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/fft_8pt_bd/ip/fft_8pt_bd_floating_point_1_0/fft_8pt_bd_floating_point_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_8pt_bd_floating_point_1_0 || ORIG_REF_NAME==fft_8pt_bd_floating_point_1_0} -quiet] -quiet

# IP: bd/fft_8pt_bd/ip/fft_8pt_bd_floating_point_2_0/fft_8pt_bd_floating_point_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_8pt_bd_floating_point_2_0 || ORIG_REF_NAME==fft_8pt_bd_floating_point_2_0} -quiet] -quiet

# IP: bd/fft_8pt_bd/ip/fft_8pt_bd_axis_dwidth_converter_1_0/fft_8pt_bd_axis_dwidth_converter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_8pt_bd_axis_dwidth_converter_1_0 || ORIG_REF_NAME==fft_8pt_bd_axis_dwidth_converter_1_0} -quiet] -quiet

# IP: bd/fft_8pt_bd/ip/fft_8pt_bd_system_ila_0_0/fft_8pt_bd_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_8pt_bd_system_ila_0_0 || ORIG_REF_NAME==fft_8pt_bd_system_ila_0_0} -quiet] -quiet

# XDC: bd/fft_8pt_bd/fft_8pt_bd_ooc.xdc
