# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.cache/wt [current_project]
set_property parent.project_path D:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zedboard:part0:1.1 [current_project]
set_property ip_output_repo d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/hdl/fft_8pt_bd_wrapper.v
add_files D:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/fft_8pt_bd.bd
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_processing_system7_0_0/fft_8pt_bd_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_dma_0_0/fft_8pt_bd_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_dma_0_0/fft_8pt_bd_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_dma_0_0/fft_8pt_bd_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_xfft_0_0/fft_8pt_bd_xfft_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/bd_0/ip/ip_1/bd_b8a1_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/bd_0/ip/ip_1/bd_b8a1_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/bd_0/ip/ip_2/bd_b8a1_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/bd_0/ip/ip_3/bd_b8a1_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/bd_0/ip/ip_4/bd_b8a1_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/bd_0/ip/ip_5/bd_b8a1_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/bd_0/ip/ip_6/bd_b8a1_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/bd_0/ip/ip_10/bd_b8a1_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/bd_0/ip/ip_11/bd_b8a1_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/bd_0/ip/ip_12/bd_b8a1_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/bd_0/ip/ip_16/bd_b8a1_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/bd_0/ip/ip_17/bd_b8a1_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/bd_0/ip/ip_18/bd_b8a1_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/bd_0/ip/ip_19/bd_b8a1_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/bd_0/ip/ip_20/bd_b8a1_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/bd_0/ip/ip_21/bd_b8a1_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/bd_0/ip/ip_22/bd_b8a1_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/bd_0/ip/ip_23/bd_b8a1_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/bd_0/ip/ip_24/bd_b8a1_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axi_smc_0/bd_0/ip/ip_25/bd_b8a1_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_rst_ps7_0_100M_0/fft_8pt_bd_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_rst_ps7_0_100M_0/fft_8pt_bd_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_rst_ps7_0_100M_0/fft_8pt_bd_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_auto_pc_0/fft_8pt_bd_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_floating_point_0_0/fft_8pt_bd_floating_point_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axis_dwidth_converter_0_0/fft_8pt_bd_axis_dwidth_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_floating_point_1_0/fft_8pt_bd_floating_point_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_floating_point_2_0/fft_8pt_bd_floating_point_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axis_dwidth_converter_1_0/fft_8pt_bd_axis_dwidth_converter_1_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_system_ila_0_0/bd_0/ip/ip_0/bd_8af0_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_system_ila_0_0/bd_0/bd_8af0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_system_ila_0_0/fft_8pt_bd_system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/fft_8pt_bd_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top fft_8pt_bd_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fft_8pt_bd_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fft_8pt_bd_wrapper_utilization_synth.rpt -pb fft_8pt_bd_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
