# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/User/Desktop/ELD LAB/LAB_8/LAB_8.srcs/sources_1/bd/Lab_8bd/ip/Lab_8bd_processing_system7_0_0/Lab_8bd_processing_system7_0_0.xci
# IP: The module: 'Lab_8bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/Desktop/ELD LAB/LAB_8/LAB_8.srcs/sources_1/bd/Lab_8bd/ip/Lab_8bd_processing_system7_0_0/Lab_8bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_8bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/User/Desktop/ELD LAB/LAB_8/LAB_8.srcs/sources_1/bd/Lab_8bd/ip/Lab_8bd_processing_system7_0_0/Lab_8bd_processing_system7_0_0.xci
# IP: The module: 'Lab_8bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/Desktop/ELD LAB/LAB_8/LAB_8.srcs/sources_1/bd/Lab_8bd/ip/Lab_8bd_processing_system7_0_0/Lab_8bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_8bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
