# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Desktop/Coding/Verilog/fft_8pt/fft_8pt.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_rst_ps7_0_100M_0/fft_8pt_bd_rst_ps7_0_100M_0.xci
# IP: The module: 'fft_8pt_bd_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Desktop/Coding/Verilog/fft_8pt/fft_8pt.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_rst_ps7_0_100M_0/fft_8pt_bd_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_8pt_bd_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Desktop/Coding/Verilog/fft_8pt/fft_8pt.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_rst_ps7_0_100M_0/fft_8pt_bd_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_8pt_bd_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Desktop/Coding/Verilog/fft_8pt/fft_8pt.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_rst_ps7_0_100M_0/fft_8pt_bd_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_8pt_bd_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Desktop/Coding/Verilog/fft_8pt/fft_8pt.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_rst_ps7_0_100M_0/fft_8pt_bd_rst_ps7_0_100M_0.xci
# IP: The module: 'fft_8pt_bd_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Desktop/Coding/Verilog/fft_8pt/fft_8pt.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_rst_ps7_0_100M_0/fft_8pt_bd_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_8pt_bd_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Desktop/Coding/Verilog/fft_8pt/fft_8pt.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_rst_ps7_0_100M_0/fft_8pt_bd_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_8pt_bd_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Desktop/Coding/Verilog/fft_8pt/fft_8pt.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_rst_ps7_0_100M_0/fft_8pt_bd_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_8pt_bd_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
