# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_fft_axi_smc_0.xci
# IP: The module: 'bd_fft_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/bd_7798.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_0/bd_7798_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_1/bd_7798_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_2/bd_7798_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_3/bd_7798_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_4/bd_7798_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_5/bd_7798_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_6/bd_7798_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_7/bd_7798_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_8/bd_7798_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_9/bd_7798_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_10/bd_7798_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_11/bd_7798_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_12/bd_7798_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_13/bd_7798_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_14/bd_7798_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_15/bd_7798_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_16/bd_7798_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_17/bd_7798_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_18/bd_7798_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_19/bd_7798_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_20/bd_7798_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_21/bd_7798_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_22/bd_7798_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_23/bd_7798_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_24/bd_7798_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_25/bd_7798_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_26/bd_7798_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_1/bd_7798_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_1/bd_7798_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_2/bd_7798_arsw_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_3/bd_7798_rsw_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_4/bd_7798_awsw_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_5/bd_7798_wsw_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_6/bd_7798_bsw_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_10/bd_7798_s00a2s_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_11/bd_7798_sarn_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_12/bd_7798_srn_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_16/bd_7798_s01a2s_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_17/bd_7798_sawn_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_18/bd_7798_swn_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_19/bd_7798_sbn_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_20/bd_7798_m00s2a_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_21/bd_7798_m00arn_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_22/bd_7798_m00rn_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_23/bd_7798_m00awn_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_24/bd_7798_m00wn_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_25/bd_7798_m00bn_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_fft_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_fft_axi_smc_0.xci
# IP: The module: 'bd_fft_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/bd_7798.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_0/bd_7798_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_1/bd_7798_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_2/bd_7798_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_3/bd_7798_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_4/bd_7798_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_5/bd_7798_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_6/bd_7798_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_7/bd_7798_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_8/bd_7798_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_9/bd_7798_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_10/bd_7798_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_11/bd_7798_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_12/bd_7798_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_13/bd_7798_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_14/bd_7798_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_15/bd_7798_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_16/bd_7798_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_17/bd_7798_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_18/bd_7798_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_19/bd_7798_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_20/bd_7798_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_21/bd_7798_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_22/bd_7798_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_23/bd_7798_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_24/bd_7798_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_25/bd_7798_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_26/bd_7798_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_1/bd_7798_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_1/bd_7798_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_2/bd_7798_arsw_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_3/bd_7798_rsw_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_4/bd_7798_awsw_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_5/bd_7798_wsw_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_6/bd_7798_bsw_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_10/bd_7798_s00a2s_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_11/bd_7798_sarn_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_12/bd_7798_srn_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_16/bd_7798_s01a2s_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_17/bd_7798_sawn_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_18/bd_7798_swn_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_19/bd_7798_sbn_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_20/bd_7798_m00s2a_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_21/bd_7798_m00arn_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_22/bd_7798_m00rn_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_23/bd_7798_m00awn_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_24/bd_7798_m00wn_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/bd_0/ip/ip_25/bd_7798_m00bn_0_ooc.xdc

# XDC: c:/Users/User/Desktop/ELD_LAB/lab9fft16/lab9fft16.srcs/sources_1/bd/bd_fft/ip/bd_fft_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_fft_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
