# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/bd_fft/bd_fft.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fft || ORIG_REF_NAME==bd_fft} -quiet] -quiet

# IP: bd/bd_fft/ip/bd_fft_processing_system7_0_0/bd_fft_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fft_processing_system7_0_0 || ORIG_REF_NAME==bd_fft_processing_system7_0_0} -quiet] -quiet

# IP: bd/bd_fft/ip/bd_fft_axi_dma_0_0/bd_fft_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fft_axi_dma_0_0 || ORIG_REF_NAME==bd_fft_axi_dma_0_0} -quiet] -quiet

# IP: bd/bd_fft/ip/bd_fft_auto_pc_0/bd_fft_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fft_auto_pc_0 || ORIG_REF_NAME==bd_fft_auto_pc_0} -quiet] -quiet

# IP: bd/bd_fft/ip/bd_fft_ps7_0_axi_periph_0/bd_fft_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fft_ps7_0_axi_periph_0 || ORIG_REF_NAME==bd_fft_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/bd_fft/ip/bd_fft_rst_ps7_0_50M_0/bd_fft_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fft_rst_ps7_0_50M_0 || ORIG_REF_NAME==bd_fft_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/bd_fft/ip/bd_fft_axi_smc_0/bd_fft_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fft_axi_smc_0 || ORIG_REF_NAME==bd_fft_axi_smc_0} -quiet] -quiet

# IP: bd/bd_fft/ip/bd_fft_xfft_0_0/bd_fft_xfft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fft_xfft_0_0 || ORIG_REF_NAME==bd_fft_xfft_0_0} -quiet] -quiet

# IP: bd/bd_fft/ip/bd_fft_xlconstant_0_0/bd_fft_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fft_xlconstant_0_0 || ORIG_REF_NAME==bd_fft_xlconstant_0_0} -quiet] -quiet

# IP: bd/bd_fft/ip/bd_fft_xlconstant_1_0/bd_fft_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fft_xlconstant_1_0 || ORIG_REF_NAME==bd_fft_xlconstant_1_0} -quiet] -quiet

# XDC: bd/bd_fft/bd_fft_ooc.xdc
