# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/User/Desktop/ELD_LAB/endsem/endsem.srcs/sources_1/bd/fft/ip/fft_floating_point_1_0/fft_floating_point_1_0.xci
# IP: The module: 'fft_floating_point_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/Desktop/ELD_LAB/endsem/endsem.srcs/sources_1/bd/fft/ip/fft_floating_point_1_0/fft_floating_point_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_floating_point_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/User/Desktop/ELD_LAB/endsem/endsem.srcs/sources_1/bd/fft/ip/fft_floating_point_1_0/fft_floating_point_1_0.xci
# IP: The module: 'fft_floating_point_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/Desktop/ELD_LAB/endsem/endsem.srcs/sources_1/bd/fft/ip/fft_floating_point_1_0/fft_floating_point_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_floating_point_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
