# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/fft8bd/fft8bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft8bd || ORIG_REF_NAME==fft8bd} -quiet] -quiet

# IP: bd/fft8bd/ip/fft8bd_processing_system7_0_0/fft8bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft8bd_processing_system7_0_0 || ORIG_REF_NAME==fft8bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/fft8bd/ip/fft8bd_axi_dma_0_0/fft8bd_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft8bd_axi_dma_0_0 || ORIG_REF_NAME==fft8bd_axi_dma_0_0} -quiet] -quiet

# IP: bd/fft8bd/ip/fft8bd_xfft_0_0/fft8bd_xfft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft8bd_xfft_0_0 || ORIG_REF_NAME==fft8bd_xfft_0_0} -quiet] -quiet

# IP: bd/fft8bd/ip/fft8bd_axi_smc_0/fft8bd_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft8bd_axi_smc_0 || ORIG_REF_NAME==fft8bd_axi_smc_0} -quiet] -quiet

# IP: bd/fft8bd/ip/fft8bd_rst_ps7_0_50M_0/fft8bd_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft8bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==fft8bd_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/fft8bd/ip/fft8bd_auto_pc_0/fft8bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft8bd_auto_pc_0 || ORIG_REF_NAME==fft8bd_auto_pc_0} -quiet] -quiet

# IP: bd/fft8bd/ip/fft8bd_ps7_0_axi_periph_0/fft8bd_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft8bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==fft8bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/fft8bd/ip/fft8bd_xlconstant_0_0/fft8bd_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft8bd_xlconstant_0_0 || ORIG_REF_NAME==fft8bd_xlconstant_0_0} -quiet] -quiet

# IP: bd/fft8bd/ip/fft8bd_xlconstant_1_0/fft8bd_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft8bd_xlconstant_1_0 || ORIG_REF_NAME==fft8bd_xlconstant_1_0} -quiet] -quiet

# XDC: bd/fft8bd/fft8bd_ooc.xdc
