# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axis_dwidth_converter_0_0/fft_8pt_bd_axis_dwidth_converter_0_0.xci
# IP: The module: 'fft_8pt_bd_axis_dwidth_converter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axis_dwidth_converter_0_0/fft_8pt_bd_axis_dwidth_converter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_8pt_bd_axis_dwidth_converter_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axis_dwidth_converter_0_0/fft_8pt_bd_axis_dwidth_converter_0_0.xci
# IP: The module: 'fft_8pt_bd_axis_dwidth_converter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ELD_final_prac/proj_one_div_1p5_plus_fft_x_sub_1p5/proj_one_div_1p5_plus_fft_x_sub_1p5.srcs/sources_1/bd/fft_8pt_bd/ip/fft_8pt_bd_axis_dwidth_converter_0_0/fft_8pt_bd_axis_dwidth_converter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_8pt_bd_axis_dwidth_converter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
