# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/User/Desktop/ELD LAB/LAB_6_hw/LAB_6_hw.srcs/sources_1/ip/fp_rec/fp_rec.xci
# IP: The module: 'fp_rec' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/Desktop/ELD LAB/LAB_6_hw/LAB_6_hw.srcs/sources_1/ip/fp_rec/fp_rec_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp_rec'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/User/Desktop/ELD LAB/LAB_6_hw/LAB_6_hw.srcs/sources_1/ip/fp_rec/fp_rec.xci
# IP: The module: 'fp_rec' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/Desktop/ELD LAB/LAB_6_hw/LAB_6_hw.srcs/sources_1/ip/fp_rec/fp_rec_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp_rec'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
